# Application Configuration
spring.application.name=Taller Mecánico Backend
server.port=8080

# Active Profile
spring.profiles.active=dev

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5434}/${DB_NAME:taller_mecanico}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Jackson Configuration (JSON)
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Santiago

# Validation Messages
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# API Documentation (Swagger)
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT RSA Keys
jwt.rsa-public-key=classpath:certs/publicKey.pem
jwt.rsa-private-key=classpath:certs/privateKey.pem

# Roles y Scopes
roles.list[0].name=ROLE_ADMIN
roles.list[0].scopes=READ,WRITE,DELETE
roles.list[1].name=ROLE_JEFE_TERMINAL
roles.list[1].scopes=READ,WRITE
roles.list[2].name=ROLE_MECANICO
roles.list[2].scopes=READ
roles.list[3].name=ROLE_CONDUCTOR
roles.list[3].scopes=READ
