export enum EstadoOrden {
    RECIBIDO = 'RECIBIDO',
    DIAGNOSTICO = 'DIAGNOSTICO',
    EN_REPARACION = 'EN_REPARACION',
    COMPLETADO = 'COMPLETADO',
    ENTREGADO = 'ENTREGADO',
    CANCELADO = 'CANCELADO',
}